config/routes.rb
Rails.application.routes.draw do
  get '/clock' => 'home#clock'
  get 'sitemap(.xml)' => 'home#sitemap', format: 'xml'

  root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = t('travels.title')
  end

  def clock
    @title = t('clock.title')
  end

  def sitemap
    render :sitemap, layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/clock.haml
.clock
  #clock
    .time.years
      .value= '00'
      .label= t('clock.years')
    .time.months
      .value= '00'
      .label= t('clock.months')
    .time.days
      .value= '00'
      .label= t('clock.days')
    .time.hours
      .value= '00'
      .label= t('clock.hours')
    .time.minutes
      .value= '00'
      .label= t('clock.minutes')
    .time.seconds
      .value= '00'
      .label= t('clock.seconds')

app/views/home/index.haml
.index
  #travel-map

app/views/layouts/_header.haml
%header{ role: 'banner' }
  .left
    .name= t('header.name')
    .links
      = link_to root_path do
        = icon('fas', 'globe-americas')
      = link_to clock_path do
        = icon('fas', 'clock')
  .center
    .avatar= image_tag 'avatar.jpg', alt: t('header.name')
  .right
    .title= @title

app/views/layouts/application.haml
!!!
%html
  %head
    %title= t('meta.title')
    %meta{ name: :description, content: t('meta.description') }
    %meta{ name: :keywords, content: t('meta.keywords') }
    %meta{ name: :viewport, content: 'width=device-width, initial-scale=1' }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag "//maps.google.com/maps/api/js?key=#{Rails.application.credentials[:google_maps]}"
    = csrf_meta_tags

  %body
    = render 'layouts/header'
    = yield